# Generated by Django 5.2.15 on 2026-06-16 16:49

import django.db.models.deletion
from django.db import migrations, models
from django.utils.text import slugify


def forwards_create_organizations(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    Organization = apps.get_model("accounts", "Organization")

    for user in User.objects.all().iterator():
        legacy_name = (user.legacy_organization_name or "").strip()
        if not legacy_name:
            legacy_name = f"Org {user.email}"

        base_slug = slugify(legacy_name) or "org"
        slug = base_slug
        counter = 1
        while Organization.objects.filter(slug=slug).exists():
            slug = f"{base_slug}-{counter}"
            counter += 1

        organization, _ = Organization.objects.get_or_create(
            slug=slug,
            defaults={"name": legacy_name},
        )
        user.organization = organization
        user.save(update_fields=["organization"])


def backwards_restore_legacy_names(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    for user in User.objects.select_related("organization").iterator():
        user.legacy_organization_name = user.organization.name if user.organization_id else ""
        user.save(update_fields=["legacy_organization_name"])


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, unique=True, verbose_name="nome")),
                ("slug", models.SlugField(max_length=255, unique=True, verbose_name="slug")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "organizzazione",
                "verbose_name_plural": "organizzazioni",
                "ordering": ["name"],
            },
        ),
        migrations.RenameField(
            model_name="user",
            old_name="organization",
            new_name="legacy_organization_name",
        ),
        migrations.AddField(
            model_name="user",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="users",
                to="accounts.organization",
                verbose_name="organizzazione",
            ),
        ),
        migrations.RunPython(forwards_create_organizations, backwards_restore_legacy_names),
        migrations.RemoveField(
            model_name="user",
            name="legacy_organization_name",
        ),
    ]
