# Generated by Django 5.2.15 on 2026-06-16 20:11

from django.db import migrations, models


def promote_first_user_per_org(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    Organization = apps.get_model("accounts", "Organization")
    for organization in Organization.objects.all():
        users = User.objects.filter(organization=organization).order_by("date_joined", "id")
        if not users.exists():
            continue
        if users.filter(role="administrator").exists():
            continue
        first_user = users.first()
        first_user.role = "administrator"
        first_user.save(update_fields=["role"])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_organization_alter_user_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('administrator', 'Administrator'), ('tender_manager', 'Tender Manager'), ('technical_writer', 'Technical Writer'), ('reviewer', 'Reviewer'), ('company_user', 'Company User'), ('scouting_manager', 'Scouting Manager')], db_index=True, default='company_user', max_length=32, verbose_name='ruolo'),
        ),
        migrations.RunPython(promote_first_user_per_org, migrations.RunPython.noop),
    ]
