server {
    listen 80;
    server_name gare.fontanebianche.today;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host:8443$request_uri;
    }
}
