# Generated by Django 5.2.15 on 2026-06-16 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cig', models.CharField(max_length=10, verbose_name='CIG')),
                ('cpv', models.CharField(max_length=8, verbose_name='CPV')),
                ('importo', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='importo')),
                ('scadenza', models.DateField(verbose_name='scadenza')),
                ('stato', models.CharField(choices=[('bozza', 'Bozza'), ('aperta', 'Aperta'), ('chiusa', 'Chiusa'), ('aggiudicata', 'Aggiudicata')], default='bozza', max_length=20, verbose_name='stato')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenders', to=settings.AUTH_USER_MODEL, verbose_name='proprietario')),
            ],
            options={
                'verbose_name': 'gara',
                'verbose_name_plural': 'gare',
                'ordering': ['-scadenza', 'cig'],
            },
        ),
    ]
