# Generated by Django 5.2.14 on 2026-06-16 14:19

import django.db.models.deletion
import tenders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='nome')),
                ('file', models.FileField(upload_to=tenders.models.tender_document_path, verbose_name='file')),
                ('original_filename', models.CharField(max_length=255, verbose_name='nome file originale')),
                ('content_type', models.CharField(blank=True, max_length=128, verbose_name='tipo MIME')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='dimensione (byte)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='caricato il')),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='tenders.tender', verbose_name='gara')),
            ],
            options={
                'verbose_name': 'documento',
                'verbose_name_plural': 'documenti',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
