# Generated by Django 5.1.6 on 2026-06-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenders", "0003_document_status_text_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="tender",
            name="ai_extracted",
            field=models.BooleanField(default=False, verbose_name="estratto AI"),
        ),
        migrations.AddField(
            model_name="tender",
            name="extracted_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="estratto il"),
        ),
    ]
