# Generated by Django 5.2.14 on 2026-06-16 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_company_extended_fields'),
        ('tenders', '0006_tender_formal_rules'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenderEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semaforo', models.CharField(choices=[('verde', 'Verde'), ('giallo', 'Giallo'), ('rosso', 'Rosso')], max_length=10, verbose_name='semaforo')),
                ('motivazione', models.TextField(verbose_name='motivazione')),
                ('dettagli', models.JSONField(blank=True, default=list, verbose_name='dettagli')),
                ('evaluated_at', models.DateTimeField(auto_now=True, verbose_name='valutato il')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='companies.company', verbose_name='azienda')),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='tenders.tender', verbose_name='gara')),
            ],
            options={
                'verbose_name': 'valutazione compatibilità',
                'verbose_name_plural': 'valutazioni compatibilità',
                'ordering': ['company__name'],
                'unique_together': {('tender', 'company')},
            },
        ),
    ]
