# Generated by Django 5.2.15 on 2026-06-16 16:49

import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
import tenders.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_organization_alter_user_organization'),
        ('companies', '0003_company_organization'),
        ('tenders', '0012_technical_relation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_index', models.PositiveIntegerField(verbose_name='indice chunk')),
                ('text', models.TextField(verbose_name='testo')),
                ('char_start', models.PositiveIntegerField(default=0, verbose_name='inizio carattere')),
                ('char_end', models.PositiveIntegerField(default=0, verbose_name='fine carattere')),
                ('page_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='numero pagina')),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True, verbose_name='embedding')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'chunk documento',
                'verbose_name_plural': 'chunk documenti',
                'ordering': ['document_id', 'chunk_index'],
            },
        ),
        migrations.CreateModel(
            name='TechnicalRelationVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(verbose_name='versione')),
                ('outline', models.JSONField(blank=True, default=tenders.models.default_technical_relation_outline, verbose_name='outline')),
                ('sections', models.JSONField(blank=True, default=tenders.models.default_technical_relation_sections, verbose_name='sezioni')),
                ('change_note', models.CharField(blank=True, max_length=255, verbose_name='nota modifica')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creato il')),
            ],
            options={
                'verbose_name': 'versione relazione tecnica',
                'verbose_name_plural': 'versioni relazione tecnica',
                'ordering': ['-version'],
            },
        ),
        migrations.AddField(
            model_name='importbatch',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='import_batches', to='accounts.organization', verbose_name='organizzazione'),
        ),
        migrations.AddField(
            model_name='tender',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenders', to='accounts.organization', verbose_name='organizzazione'),
        ),
        migrations.AddConstraint(
            model_name='tender',
            constraint=models.UniqueConstraint(fields=('organization', 'cig'), name='unique_cig_per_organization'),
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='tenders.document', verbose_name='documento'),
        ),
        migrations.AddField(
            model_name='technicalrelationversion',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='technical_relation_versions', to='companies.company', verbose_name='azienda'),
        ),
        migrations.AddField(
            model_name='technicalrelationversion',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='technical_relation_versions', to=settings.AUTH_USER_MODEL, verbose_name='creato da'),
        ),
        migrations.AddField(
            model_name='technicalrelationversion',
            name='relation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='tenders.technicalrelation', verbose_name='relazione tecnica'),
        ),
        migrations.AddIndex(
            model_name='documentchunk',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='doc_chunk_emb_hnsw_idx', opclasses=['vector_cosine_ops']),
        ),
        migrations.AddConstraint(
            model_name='documentchunk',
            constraint=models.UniqueConstraint(fields=('document', 'chunk_index'), name='unique_chunk_per_document'),
        ),
        migrations.AddConstraint(
            model_name='technicalrelationversion',
            constraint=models.UniqueConstraint(fields=('relation', 'version'), name='unique_technical_relation_version'),
        ),
    ]
