# Generated by Django 5.2.15 on 2026-06-16 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0015_requirement_extended_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationCriterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('livello', models.CharField(choices=[('criterio', 'Criterio'), ('subcriterio', 'Subcriterio'), ('microcriterio', 'Microcriterio')], max_length=16, verbose_name='livello')),
                ('titolo', models.CharField(max_length=500, verbose_name='titolo')),
                ('descrizione', models.TextField(blank=True, verbose_name='descrizione')),
                ('punteggio_massimo', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='punteggio massimo')),
                ('punteggio_discrezionale', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='punteggio discrezionale')),
                ('punteggio_tabellare', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='punteggio tabellare')),
                ('soglia_minima', models.CharField(blank=True, max_length=255, verbose_name='soglia minima')),
                ('elementi_premianti', models.JSONField(blank=True, default=list, verbose_name='elementi premianti')),
                ('documento_origine', models.CharField(blank=True, max_length=255, verbose_name='documento origine')),
                ('pagina_origine', models.CharField(blank=True, max_length=50, verbose_name='pagina origine')),
                ('paragrafo_origine', models.CharField(blank=True, max_length=100, verbose_name='paragrafo origine')),
                ('ordine', models.PositiveIntegerField(default=0, verbose_name='ordine')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_criteria', to='tenders.document', verbose_name='documento sorgente')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='tenders.evaluationcriterion', verbose_name='elemento padre')),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_criteria', to='tenders.tender', verbose_name='gara')),
            ],
            options={
                'verbose_name': 'criterio di valutazione',
                'verbose_name_plural': 'criteri di valutazione',
                'ordering': ['ordine', 'id'],
            },
        ),
    ]
