# Generated by Django 5.2.15 on 2026-06-19 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0018_tender_analysis_pipeline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importbatch',
            name='source',
            field=models.CharField(choices=[('scouting', 'Scouting'), ('telemat', 'Telemat'), ('welfare', 'Welfare')], max_length=20, verbose_name='fonte'),
        ),
        migrations.AlterField(
            model_name='tender',
            name='source',
            field=models.CharField(choices=[('manual', 'Manuale'), ('scouting', 'Scouting'), ('telemat', 'Telemat'), ('welfare', 'Welfare')], default='manual', max_length=20, verbose_name='fonte'),
        ),
    ]
