from django.urls import path

from .views import (
    DocumentDetailView,
    DocumentDownloadView,
    DocumentListCreateView,
    DocumentSearchView,
    RequirementDetailView,
    RequirementListView,
    RequirementMatrixView,
    EvaluationCriterionDetailView,
    EvaluationCriterionTreeView,
    ScoutingImportListCreateView,
    ScoutingScoreView,
    TelematImportListCreateView,
    WelfareImportListCreateView,
    TechnicalRelationDetailView,
    TechnicalRelationOutlineGenerateView,
    TechnicalRelationValidateView,
    TechnicalRelationVersionListView,
    TechnicalRelationVersionRestoreView,
    TenderDetailView,
    TenderEvaluationListView,
    TenderEvaluationRunView,
    TenderExportOptionsView,
    TenderExportView,
    TenderListCreateView,
)

urlpatterns = [
    path("tenders/", TenderListCreateView.as_view(), name="tender-list"),
    path("tenders/<int:pk>/", TenderDetailView.as_view(), name="tender-detail"),
    path(
        "tenders/<int:tender_pk>/export/options/",
        TenderExportOptionsView.as_view(),
        name="tender-export-options",
    ),
    path(
        "tenders/<int:tender_pk>/export/",
        TenderExportView.as_view(),
        name="tender-export",
    ),
    path(
        "tenders/<int:tender_pk>/documents/",
        DocumentListCreateView.as_view(),
        name="tender-document-list",
    ),
    path(
        "tenders/<int:tender_pk>/documents/<int:pk>/",
        DocumentDetailView.as_view(),
        name="tender-document-detail",
    ),
    path(
        "tenders/<int:tender_pk>/documents/<int:pk>/download/",
        DocumentDownloadView.as_view(),
        name="tender-document-download",
    ),
    path(
        "tenders/<int:tender_pk>/requirements/",
        RequirementListView.as_view(),
        name="tender-requirement-list",
    ),
    path(
        "tenders/<int:tender_pk>/requirements/<int:pk>/",
        RequirementDetailView.as_view(),
        name="tender-requirement-detail",
    ),
    path(
        "tenders/<int:tender_pk>/requirements-matrix/",
        RequirementMatrixView.as_view(),
        name="tender-requirement-matrix",
    ),
    path(
        "tenders/<int:tender_pk>/evaluation-criteria/",
        EvaluationCriterionTreeView.as_view(),
        name="tender-evaluation-criteria-tree",
    ),
    path(
        "tenders/<int:tender_pk>/evaluation-criteria/<int:pk>/",
        EvaluationCriterionDetailView.as_view(),
        name="tender-evaluation-criterion-detail",
    ),
    path(
        "tenders/<int:tender_pk>/evaluations/",
        TenderEvaluationListView.as_view(),
        name="tender-evaluation-list",
    ),
    path(
        "tenders/<int:tender_pk>/evaluations/evaluate/",
        TenderEvaluationRunView.as_view(),
        name="tender-evaluation-run",
    ),
    path(
        "tenders/<int:tender_pk>/technical-relation/",
        TechnicalRelationDetailView.as_view(),
        name="tender-technical-relation",
    ),
    path(
        "tenders/<int:tender_pk>/technical-relation/outline/",
        TechnicalRelationOutlineGenerateView.as_view(),
        name="tender-technical-relation-outline",
    ),
    path(
        "tenders/<int:tender_pk>/technical-relation/validate/",
        TechnicalRelationValidateView.as_view(),
        name="tender-technical-relation-validate",
    ),
    path(
        "tenders/<int:tender_pk>/technical-relation/versions/",
        TechnicalRelationVersionListView.as_view(),
        name="tender-technical-relation-versions",
    ),
    path(
        "tenders/<int:tender_pk>/technical-relation/versions/<int:version>/restore/",
        TechnicalRelationVersionRestoreView.as_view(),
        name="tender-technical-relation-version-restore",
    ),
    path(
        "scouting/imports/",
        ScoutingImportListCreateView.as_view(),
        name="scouting-import-list",
    ),
    path(
        "scouting/score/",
        ScoutingScoreView.as_view(),
        name="scouting-score",
    ),
    path(
        "telemat/imports/",
        TelematImportListCreateView.as_view(),
        name="telemat-import-list",
    ),
    path(
        "welfare/imports/",
        WelfareImportListCreateView.as_view(),
        name="welfare-import-list",
    ),
    path(
        "search/documents/",
        DocumentSearchView.as_view(),
        name="document-search",
    ),
]
