# Generated by Django 5.2.15 on 2026-06-16 18:54

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_organization_alter_user_organization'),
        ('companies', '0006_companydocument'),
        ('tenders', '0015_requirement_extended_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consorzio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=255, verbose_name='denominazione consorzio')),
                ('note', models.TextField(blank=True, verbose_name='note')),
                ('mandanti', models.JSONField(blank=True, default=list, help_text='[{"company_id": int, "quota_partecipazione": float, "quota_esecuzione": float}]', verbose_name='mandanti')),
                ('ripartizione_requisiti', models.JSONField(blank=True, default=dict, help_text='Mappa requirement_id → company_id responsabile', verbose_name='ripartizione requisiti')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mandataria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consorzi_as_mandataria', to='companies.company', verbose_name='impresa mandataria / capogruppo')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consorzi', to='accounts.organization', verbose_name='organizzazione')),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consorzi', to='tenders.tender', verbose_name='gara')),
            ],
            options={
                'verbose_name': 'consorzio',
                'verbose_name_plural': 'consorzi',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='RTI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=255, verbose_name='denominazione RTI')),
                ('note', models.TextField(blank=True, verbose_name='note')),
                ('ripartizione_requisiti', models.JSONField(blank=True, default=dict, help_text='Mappa requirement_id → company_id responsabile', verbose_name='ripartizione requisiti')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mandataria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rti_as_mandataria', to='companies.company', verbose_name='impresa mandataria')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rti_groups', to='accounts.organization', verbose_name='organizzazione')),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rti_groups', to='tenders.tender', verbose_name='gara')),
            ],
            options={
                'verbose_name': 'RTI',
                'verbose_name_plural': 'RTI',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ImpresaAusiliaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requisiti_coperti', models.JSONField(blank=True, default=list, help_text='Lista di requirement_id coperti tramite avvalimento', verbose_name='requisiti coperti')),
                ('note', models.TextField(blank=True, verbose_name='note')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('impresa_ausiliaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avvalimenti_foriti', to='companies.company', verbose_name='impresa ausiliaria')),
                ('impresa_principale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avvalimenti_ricevuti', to='companies.company', verbose_name='impresa principale')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imprese_ausiliarie', to='accounts.organization', verbose_name='organizzazione')),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imprese_ausiliarie', to='tenders.tender', verbose_name='gara')),
            ],
            options={
                'verbose_name': 'impresa ausiliaria',
                'verbose_name_plural': 'imprese ausiliarie',
                'ordering': ['-updated_at'],
                'constraints': [models.UniqueConstraint(fields=('tender', 'impresa_principale', 'impresa_ausiliaria'), name='unique_avvalimento_pair')],
            },
        ),
        migrations.CreateModel(
            name='RTIMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruolo', models.CharField(choices=[('mandataria', 'Mandataria'), ('mandante', 'Mandante')], max_length=16, verbose_name='ruolo')),
                ('quota_partecipazione', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='quota partecipazione %')),
                ('quota_esecuzione', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='quota esecuzione %')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rti_memberships', to='companies.company', verbose_name='impresa')),
                ('rti', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='participations.rti', verbose_name='RTI')),
            ],
            options={
                'verbose_name': 'componente RTI',
                'verbose_name_plural': 'componenti RTI',
                'ordering': ['ruolo', 'company__name'],
                'constraints': [models.UniqueConstraint(fields=('rti', 'company'), name='unique_rti_member_company')],
            },
        ),
    ]
