# Generated by Django 5.2.15 on 2026-06-16 19:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_organization_alter_user_organization'),
        ('tenders', '0016_evaluationcriterion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AiGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_id', models.CharField(blank=True, default='', max_length=64, verbose_name='ID sezione')),
                ('action_type', models.CharField(choices=[('technical_criterion', 'Generazione criterio tecnico'), ('improvement_proposal', 'Proposta migliorie'), ('content_adaptation', 'Adattamento contenuti'), ('report_structure', 'Generazione struttura relazione')], db_index=True, max_length=32, verbose_name='azione')),
                ('prompt', models.TextField(verbose_name='prompt')),
                ('prompt_messages', models.JSONField(blank=True, default=list, verbose_name='messaggi prompt')),
                ('model', models.CharField(max_length=128, verbose_name='modello')),
                ('provider', models.CharField(choices=[('openai', 'OpenAI'), ('azure_openai', 'Azure OpenAI')], max_length=32, verbose_name='provider')),
                ('response', models.TextField(verbose_name='risposta')),
                ('sources', models.JSONField(blank=True, default=list, verbose_name='fonti RAG')),
                ('rag_chunks', models.JSONField(blank=True, default=list, verbose_name='chunk RAG')),
                ('prompt_tokens', models.PositiveIntegerField(blank=True, null=True, verbose_name='token prompt')),
                ('completion_tokens', models.PositiveIntegerField(blank=True, null=True, verbose_name='token risposta')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='generato il')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_generations', to='accounts.organization', verbose_name='organizzazione')),
                ('tender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_generations', to='tenders.tender', verbose_name='gara')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_generations', to=settings.AUTH_USER_MODEL, verbose_name='utente')),
            ],
            options={
                'verbose_name': 'generazione AI',
                'verbose_name_plural': 'generazioni AI',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'tender', '-created_at'], name='ai_aigenera_organiz_7d0ed4_idx'), models.Index(fields=['organization', 'action_type', '-created_at'], name='ai_aigenera_organiz_edfbdc_idx')],
            },
        ),
    ]
