# Generated by Django 5.2.14 on 2026-06-16 14:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ragione sociale')),
                ('fatturato', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='fatturato annuo')),
                ('certificazioni', models.JSONField(blank=True, default=list, verbose_name='certificazioni')),
                ('servizi', models.JSONField(blank=True, default=list, verbose_name='servizi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to=settings.AUTH_USER_MODEL, verbose_name='proprietario')),
            ],
            options={
                'verbose_name': 'azienda',
                'verbose_name_plural': 'aziende',
                'ordering': ['name'],
            },
        ),
    ]
