# Generated by Django 5.2.15 on 2026-06-16 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='ccnl',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='CCNL applicato'),
        ),
        migrations.AddField(
            model_name='company',
            name='dipendenti',
            field=models.JSONField(blank=True, default=list, help_text='Lista di {"categoria": str, "numero": int}', verbose_name='dipendenti'),
        ),
        migrations.AddField(
            model_name='company',
            name='esperienze',
            field=models.JSONField(blank=True, default=list, help_text='Esperienze pregresse su appalti simili', verbose_name='esperienze'),
        ),
    ]
