# Generated by Django 5.2.14 on 2026-06-16 16:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicalOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='titolo')),
                ('category', models.CharField(choices=[('organizzazione', 'Organizzazione servizio'), ('metodologia', 'Metodologia operativa'), ('personale', 'Personale e formazione'), ('attrezzature', 'Attrezzature e mezzi'), ('sicurezza', 'Sicurezza sul lavoro'), ('ambiente', 'Tutela ambientale'), ('qualita', 'Sistema qualità'), ('altro', 'Altro')], default='altro', max_length=32, verbose_name='categoria')),
                ('content', models.TextField(blank=True, default='', verbose_name='contenuto')),
                ('tags', models.JSONField(blank=True, default=list, help_text='Lista di stringhe per la ricerca e il filtraggio', verbose_name='tag')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technical_offers', to=settings.AUTH_USER_MODEL, verbose_name='proprietario')),
            ],
            options={
                'verbose_name': 'offerta tecnica',
                'verbose_name_plural': 'offerte tecniche',
                'ordering': ['-updated_at', 'title'],
            },
        ),
    ]
