# Generated by Django 5.2.15 on 2026-06-16 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_organization_alter_user_organization'),
        ('technical_offers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='technicaloffer',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='technical_offers', to='accounts.organization', verbose_name='organizzazione'),
        ),
    ]
