# Generated by Django 5.2.15 on 2026-06-16 19:07

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_organization_alter_user_organization'),
        ('technical_offers', '0003_populate_technicaloffer_organization'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='technicaloffer',
            name='anno',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1990), django.core.validators.MaxValueValidator(2100)], verbose_name='anno'),
        ),
        migrations.AddField(
            model_name='technicaloffer',
            name='durata',
            field=models.CharField(blank=True, default='', help_text='Es. "24 mesi", "3 anni"', max_length=100, verbose_name='durata'),
        ),
        migrations.AddField(
            model_name='technicaloffer',
            name='ente_appaltante',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='ente appaltante'),
        ),
        migrations.AddField(
            model_name='technicaloffer',
            name='innovativita',
            field=models.PositiveSmallIntegerField(default=3, help_text='Valutazione 1-5', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='innovatività'),
        ),
        migrations.AddField(
            model_name='technicaloffer',
            name='parole_chiave',
            field=models.JSONField(blank=True, default=list, help_text='Parole chiave per ricerca semantica e RAG', verbose_name='parole chiave'),
        ),
        migrations.AddField(
            model_name='technicaloffer',
            name='punteggio_ottenuto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='punteggio ottenuto'),
        ),
        migrations.AddField(
            model_name='technicaloffer',
            name='rag_metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Metadati strutturati per il modulo RAG', verbose_name='metadati RAG'),
        ),
        migrations.AddField(
            model_name='technicaloffer',
            name='rag_text',
            field=models.TextField(blank=True, default='', help_text='Testo consolidato per embedding e retrieval', verbose_name='testo indicizzazione RAG'),
        ),
        migrations.AddField(
            model_name='technicaloffer',
            name='riutilizzabilita',
            field=models.PositiveSmallIntegerField(default=3, help_text='Valutazione 1-5', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='riutilizzabilità'),
        ),
        migrations.AddField(
            model_name='technicaloffer',
            name='settore',
            field=models.CharField(blank=True, choices=[('pulizie', 'Pulizie e sanificazione'), ('verde', 'Verde e parchi'), ('manutenzione', 'Manutenzione edile'), ('facility', 'Facility management'), ('it', 'ICT e software'), ('consulenza', 'Consulenza professionale'), ('trasporti', 'Trasporti e logistica'), ('sanita', 'Sanità e sociale'), ('cultura', 'Cultura e eventi'), ('altro', 'Altro')], default='', max_length=32, verbose_name='settore'),
        ),
        migrations.AddField(
            model_name='technicaloffer',
            name='tipologia_servizio',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='tipologia servizio'),
        ),
        migrations.AddField(
            model_name='technicaloffer',
            name='valore_appalto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='valore appalto'),
        ),
        migrations.AddIndex(
            model_name='technicaloffer',
            index=models.Index(fields=['category', 'settore'], name='technical_o_categor_ce6273_idx'),
        ),
        migrations.AddIndex(
            model_name='technicaloffer',
            index=models.Index(fields=['anno'], name='technical_o_anno_6a215c_idx'),
        ),
        migrations.AddIndex(
            model_name='technicaloffer',
            index=models.Index(fields=['ente_appaltante'], name='technical_o_ente_ap_3f4ff6_idx'),
        ),
    ]
