# Generated by Django 5.2.15 on 2026-06-16 19:16

import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_organization_alter_user_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='RagChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('tender_document', 'Documento gara'), ('technical_offer', 'Offerta tecnica'), ('requirement', 'Requisito'), ('company', 'Dati aziendali')], db_index=True, max_length=32, verbose_name='tipo sorgente')),
                ('source_id', models.PositiveIntegerField(db_index=True, verbose_name='ID sorgente')),
                ('chunk_index', models.PositiveIntegerField(default=0, verbose_name='indice chunk')),
                ('title', models.CharField(max_length=512, verbose_name='titolo')),
                ('text', models.TextField(verbose_name='testo')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadati')),
                ('embedding', pgvector.django.vector.VectorField(dimensions=384)),
                ('indexed_at', models.DateTimeField(auto_now=True, verbose_name='indicizzato il')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rag_chunks', to='accounts.organization', verbose_name='organizzazione')),
            ],
            options={
                'verbose_name': 'chunk RAG',
                'verbose_name_plural': 'chunk RAG',
                'ordering': ['source_type', 'source_id', 'chunk_index'],
                'indexes': [pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='rag_chunk_embedding_hnsw_idx', opclasses=['vector_cosine_ops']), models.Index(fields=['organization', 'source_type'], name='rag_ragchun_organiz_cb7501_idx'), models.Index(fields=['organization', 'source_type', 'source_id'], name='rag_ragchun_organiz_407675_idx')],
                'constraints': [models.UniqueConstraint(fields=('source_type', 'source_id', 'chunk_index'), name='unique_rag_chunk_per_source')],
            },
        ),
    ]
